### ISSUE TITLE
500 Internal Server Error when trying to check song splits

### ISSUE THREAD

**Issue by wileyfoxyx** [AdelHashem/Spotify-Link-To-Musixmatch-Track-and-Album-webApp#10]

**Comment by AdelHashem** [comment]
I have not handled the different cases we might face yet, but this occurs when the track is not in the catalog yet.
If you sure that it's there please provide me the Spotify links

**Comment by AdelHashem** [comment]
most of cases should be handled now. If you faced any case not handled yet please let me know
Thanks!
