### ISSUE TITLE
Status code 401 Unauthorized is returned on specific websites

### ISSUE THREAD

**Issue by AimilDimitrak** [AdelHashem/Spotify-Link-To-Musixmatch-Track-and-Album-webApp#11]
Hello there!

Today I tried to import a song from Spotify through the Vercel app, and it returned a 401 status code. 
The same happened to the `pythonanywhere.com` page.
The only webside which didn't return a 401 status code at all was the app hosted on Render.
The last website listed doesn't work, so no comments on that.

Best regards.

**Comment by AdelHashem** [comment]
Yesterday, we hit the MXM API limit for all domains.

**Comment by AdelHashem** [comment]
I've edited the 401 message to tell that we hit the limit.
