### ISSUE TITLE
Contributing instructions

### ISSUE THREAD

**Issue by federico-ntr** [AdelHashem/Spotify-Link-To-Musixmatch-Track-and-Album-webApp#13]
Hello,
I'm not familiar at all with Flask development, but I would like to contribute to `static` and `templates`. It would be nice if you added a guide which explains how to setup the project environment locally and some contributing guidelines.

Thanks :)

**Comment by AdelHashem** [comment]
- install python-dotenv
`pip install python-dotenv
`
- Create .env

```
#.env
MXM_API=Your_MXM_API_Key
MXM_API2=Your_MXM_API_Key
```
- Create .flaskenv
```
#.flaskenv
FLASK_APP=app
FLASK_DEBUG = True
```

- Run the App using
`flask run`
also u can comment `asyncio.run(serve(app, Config()))`
then uncomment `app.run(debug=True)` and just run the app.py

# For contributing
- You can just provide what you made in the pull request
- then we can test and merge
