### ISSUE TITLE
Add musixmatch beta link to the website

### ISSUE THREAD

**Issue by sulvii** [AdelHashem/Spotify-Link-To-Musixmatch-Track-and-Album-webApp#15]
Add beta link too, like it'll show the link for the beta site.
This is an easy solution, you just have to replace '`www.musixmatch.com`' with '`beta.musixmatch.com`'

Though this is not a required feature but some people may look for the beta link, so I think this would be great.

**Comment by AdelHashem** [comment]
#16 
[https://spotify-link-to-musixmatch-track-and-albu-git-22ef09-adelhashem.vercel.app/](url)
All good?
